### Author: Alexander Kanitz
### Created: 13-MAY-2013
### Modified: 13-MAY-2013
### Description: Plots window position counts generated by overlap_counts_window_around_pos_vs_bed.pl and derivatives. A sample and control are plotted for the indicated window size (centered on the mid-point). Average count and count fractions will be plotted, as well as total counts for each individual genome position (CAREFUL: 1 plot per row of input data!)
### Arguments: 1./2. Sample and control output table files generated by overlap_counts_window_around_pos_vs_bed.pl (CAREFUL: sample and control data tables have to have the same dimensions!) [PATH]; 3./4. Group names (e.g. "sample" and "control") in the same order as 1./2. [STRING]; 5. name/id representing the set of genome positions that are plotted [STRING]; 6. window size (1 will be added automatically for the center position, so use e.g. 1000 to plot from -500 to +500) [INTEGER]; 7. (existing!) output path without trailing '/' [PATH]
### Output: Plots of average and individual window position counts centered on the positions specified in the input file; the actual window size is thus the indicated window size + 1; a window size parameter of 100,000 will plot windows of 100,001 and 10,001
### Usage: Rscript ./plot_window_position_count_comparisons.R ./sample.tab ./control.tab sample control top100 1000 ./out

### A. Pre-requisites
# Initialize command line arguments
args <- commandArgs(trailingOnly=TRUE)
## Pass arguments
smpl_cut_filename <- "AsiSI_cut_reads_induced_window_positon_counts"
ctrl_cut_filename <- "AsiSI_cut_reads_uninduced_window_positon_counts"
smpl_uncut_filename <- "AsiSI_uncut_reads_induced_window_positon_counts"
ctrl_uncut_filename <- "AsiSI_uncut_reads_uninduced_window_positon_counts"
comp <- c("induced", "uninduced")
set <- c("cut", "uncut")
win_size <- 250
out_path <- "."
## Build output path name & make directory
path_frct <- paste(out_path, "/comparison_average_fraction/", sep="")
dir.create <- dir.create(path_frct, showWarnings = FALSE, mode = "0755")
## Customized plotting function
plot_window_compare <- function(x, smpl1, ctrl1, smpl2, ctrl2, out_path, prefix, set, comparison, ylab="") {
	# Build filename
	name <- paste(prefix, set[1], "vs", set[2], "and", comparison[1], "vs", comparison[2], win, sep="_")
	# Build plot title
	main <-	paste("Sets:", set[1], "(black) vs", set[2], "(red)", "\nComparison:", comparison[1], "vs", comparison[2], "(dashed)", sep=" ") 
	## Obtain minimum/maximum values for y axis
	ymin = min(smpl1, ctrl1, smpl2, ctrl2)
	ymax = max(smpl1, ctrl1, smpl2, ctrl2)
	# Open pdf printer device
	pdf(paste(out_path, name, ".pdf", sep=""), width=20, height=6)
	# Plot sample
	plot(x, smpl1, type="l", main=main, xlab="Position relative to the reference", ylab=ylab, ylim=c(ymin, ymax))
	# Plot control
	lines(x, ctrl1, lty=2)
	lines(x, smpl2, col="red")
	lines(x, ctrl2, col="red", lty=2)
	# Close pdf printer
	dev.off()
}
###

win_size <- 250

### B. Load and test data
# Read data table
smpl_cut_df <- read.table(smpl_cut_filename, sep=" ", row.names=1)
ctrl_cut_df <- read.table(ctrl_cut_filename, sep=" ", row.names=1)
smpl_uncut_df <- read.table(smpl_uncut_filename, sep=" ", row.names=1)
ctrl_uncut_df <- read.table(ctrl_uncut_filename, sep=" ", row.names=1)
# Abort execution if input data sets are not of equal width
if (! ncol(smpl_cut_df) == ncol(ctrl_cut_df) && ncol(smpl_cut_df) == ncol(smpl_uncut_df) && ncol(smpl_cut_df) == ncol(ctrl_uncut_df)) stop("The dimensions of the sample and control data sets do not match.\nExecution aborted.\n")
# Assign column number to dedicated variable
cols <- ncol(smpl_cut_df)
###

### C. Get/test/set window size
# If indicated window size is bigger than the number of columns in the input files + 1... 
if (cols + 1 < win_size) {
	# ...set plot window size to number of columns
	win <- cols
	# ...and print warning message
	cat("Warning: The input data sets are not wide enough to cover the specified plot window size. The primary window size has been reduced to the maximum number of available positions: \n", win, "\n")
# Else set primary window size to specified window size + 1
} else win <- win_size + 1
###

### D. Data preparation
# Generate x values (from minus to plus half of indicated window size; e.g. for size = 10000, plot from -5000 to 5000; note that 'win' is the indicated size + 1)
x <- seq(-((win - 1) / 2), (win - 1) / 2, 1)
## Subset data (if applicable)
if (!win == cols) {
	# Calculate length of flanking regions in input data sets that will not be plotted
	cols_out <- (cols - win) / 2
	# Generate logical vector indicating which columns to subset
	cols_select <- c(rep(FALSE, cols_out), rep(TRUE, win), rep(FALSE,cols_out))
	## Select only those columns of the dataframes that contain data that falls within the indicated window size
	smpl_cut_df <- subset(smpl_cut_df, select=cols_select)
	ctrl_cut_df <- subset(ctrl_cut_df, select=cols_select)
	smpl_uncut_df <- subset(smpl_uncut_df, select=cols_select)
	ctrl_uncut_df <- subset(ctrl_uncut_df, select=cols_select)
}
## Normalization: Divide counts in each row by the sum of counts in the row (ifelse avoids 'NaN' values in case of 0 division)
smpl_cut_norm_df = smpl_cut_df / ifelse(rowSums(smpl_cut_df) == 0, 1, rowSums(smpl_cut_df))
ctrl_cut_norm_df = ctrl_cut_df / ifelse(rowSums(ctrl_cut_df) == 0, 1, rowSums(ctrl_cut_df))
smpl_uncut_norm_df = smpl_uncut_df / ifelse(rowSums(smpl_uncut_df) == 0, 1, rowSums(smpl_uncut_df))
ctrl_uncut_norm_df = ctrl_uncut_df / ifelse(rowSums(ctrl_uncut_df) == 0, 1, rowSums(ctrl_uncut_df))
## Compute averages (fractions)
smpl_cut_norm_y <- colSums(smpl_cut_norm_df) / nrow(smpl_cut_norm_df)
ctrl_cut_norm_y <- colSums(ctrl_cut_norm_df) / nrow(ctrl_cut_norm_df)
smpl_uncut_norm_y <- colSums(smpl_uncut_norm_df) / nrow(smpl_uncut_norm_df)
ctrl_uncut_norm_y <- colSums(ctrl_uncut_norm_df) / nrow(ctrl_uncut_norm_df)
###


### E. Plotting
## Plotting function calls for count averages and fractions
plot_window_compare(x=x, smpl1=smpl_cut_norm_y, ctrl1=ctrl_cut_norm_y, smpl2=smpl_uncut_norm_y, ctrl2=ctrl_uncut_norm_y, out_path=path_frct, prefix="count_fractions", set=set, comparison=comp, ylab="Read count fraction")
###