### Author: Alexander Kanitz
### Created: 04-FEB-2013
### Modified: 04-FEB-2013
### Description: Plots window position counts generated by overlap_counts_window_around_pos_vs_bed.pl and derivatives. A sample and control are plotted for the indicated window size (centered on the mid-point). Average count and count fractions will be plotted, as well as total counts for each individual genome position (CAREFUL: 1 plot per row of input data!)
### Arguments: 1./2. Sample and control output table files generated by overlap_counts_window_around_pos_vs_bed.pl (CAREFUL: sample and control data tables have to have the same dimensions!) [PATH]; 3./4. Group names (e.g. "sample" and "control") in the same order as 1./2. [STRING]; 5. name/id representing the set of genome positions that are plotted [STRING]; 6. window size (1 will be added automatically for the center position, so use e.g. 1000 to plot from -500 to +500) [INTEGER]; 7. (existing!) output path without trailing '/' [PATH]
### Output: Plots of average and individual window position counts the positions specified in the input file; windows to be plotted are of the indicated size and of 10% of that value, both centered around the window mid-point (0); the actual window size is thus the indicated window size + 1; a window size parameter of 100,000 will plot windows of 100,001 and 10,001
### Usage: Rscript ./plot_window_position_counts.R ./sample.tab ./control.tab sample control top100 1000 ./out

### A. Command line arguments
# Initialize command line arguments
args <- commandArgs(trailingOnly=TRUE)
## Pass arguments
smpl_filename <- as.character(args[1])
ctrl_filename <- as.character(args[2])
comp <- c(as.character(args[3]), as.character(args[4]))
set <- as.character(args[5])
win_size <- as.integer(args[6])
out_path <- as.character(args[7])
###

### B. Load and test data
# Read data table
smpl_df <- read.table(smpl_filename, sep=" ", row.names=1) #, fill=TRUE) # FILL SHOULD NOT BE NEEDED! IF CAUSES PROBLEMS, CHANGE "OVERLAP_COUNTS_WINDOW_AROUND_POS_VS_BED.PL" SCRIPT
ctrl_df <- read.table(ctrl_filename, sep=" ", row.names=1) #, fill=TRUE) # FILL SHOULD NOT BE NEEDED! IF CAUSES PROBLEMS, CHANGE "OVERLAP_COUNTS_WINDOW_AROUND_POS_VS_BED.PL" SCRIPT
# Abort execution if input data sets are not of equal size
if (! all(dim(smpl_df) == dim(ctrl_df)) ) stop("The dimensions of the sample and control data sets do not match.\nExecution aborted.\n")
# Assign column number to dedicated variable
cols <- ncol(smpl_df)
###

### C. Get/test/set window size
# If indicated window size is bigger than the number of columns in the input files + 1... 
if (cols + 1 < win_size) {
	# ...set plot window size to number of columns
	win <- cols
	# ...and print warning message
	cat("Warning: The input data sets are not wide enough to cover the specified plot window size. The primary window size has been reduced to the maximum number of available positions: \n", win, "\n")
# Else set primary window size to specified window size + 1
} else win <- win_size + 1
###

### D. Data preparation
# Generate x values (from minus to plus half of indicated window size; e.g. for size = 10000, plot from -5000 to 5000; note that 'win' is the indicated size + 1)
x <- seq(-((win - 1) / 2), (win - 1) / 2, 1)
## Subset data (if applicable)
if (!win == cols) {
	# Calculate length of flanking regions in input data sets that will not be plotted
	cols_out <- (cols - win) / 2
	# Generate logical vector indicating which columns to subset
	cols_select <- c(rep(FALSE, cols_out), rep(TRUE, win), rep(FALSE,cols_out))
	## Select only those columns of the dataframes that contain data that falls within the indicated window size
	smpl_df <- subset(smpl_df, select=cols_select)
	ctrl_df <- subset(ctrl_df, select=cols_select)
}
## Normalization: Divide counts in each row by the sum of counts in the row (ifelse avoids 'NaN' values in case of 0 division)
smpl_norm_df = smpl_df / ifelse(rowSums(smpl_df) == 0, 1, rowSums(smpl_df))
ctrl_norm_df = ctrl_df / ifelse(rowSums(ctrl_df) == 0, 1, rowSums(ctrl_df))
## Compute averages (counts)
smpl_y <- colSums(smpl_df) / nrow(smpl_df)
ctrl_y <- colSums(ctrl_df) / nrow(ctrl_df)
## Compute averages (fractions)
smpl_norm_y <- colSums(smpl_norm_df) / nrow(smpl_norm_df)
ctrl_norm_y <- colSums(ctrl_norm_df) / nrow(ctrl_norm_df)
###

### E. Plotting
## Customized plotting function
plot_window_compare <- function(x, smpl, ctrl, out_path, prefix, set, comparison=c("sample", "control"), ylab="") {
	# Build filename
	name <- paste(prefix, set, comparison[1], "vs", comparison[2], win, sep="_")
	# Build plot title
	main <-	paste("Set:", set, "\nComparison:", comparison[1], "(black) vs", comparison[2], "(red)", sep=" ") 
	## Obtain minimum/maximum values for y axis
	ymin = min(smpl, ctrl)
	ymax = max(smpl, ctrl)
	# Open pdf printer device
	pdf(paste(out_path, name, ".pdf", sep=""), width=20, height=6)
	# Plot sample
	plot(x, smpl, type="l", main=main, xlab="Position relative to the reference", ylab=ylab, ylim=c(ymin, ymax))
	# Plot control
	lines(x, ctrl, lty=2, col="red")
	# Close pdf printer
	dev.off()
}
## Build output path names
path_cts <- paste(out_path, "/comparison_average_counts/", sep="")
path_frct <- paste(out_path, "/comparison_average_fraction/", sep="")
path_ind <- paste(out_path, "/comparison_individual_counts/", sep="")
## Make directories
dir.create <- dir.create(path_cts, showWarnings = FALSE, mode = "0755")
dir.create <- dir.create(path_frct, showWarnings = FALSE, mode = "0755")
dir.create <- dir.create(path_ind, showWarnings = FALSE, mode = "0755")
## Plotting function calls for count averages and fractions
plot_window_compare(x=x, smpl=smpl_y, ctrl=ctrl_y, out_path=path_cts, prefix="count_averages", set=set, comparison=comp, ylab="Read count average")		
plot_window_compare(x=x, smpl=smpl_norm_y, ctrl=ctrl_norm_y, out_path=path_frct, prefix="count_fractions", set=set, comparison=comp, ylab="Read count fraction")
# Plot separate count windows for individual genome positions
dump <- sapply(rownames(smpl_df), function(coord) plot_window_compare(x=x, smpl=smpl_df[coord, ], ctrl=ctrl_df[coord, ], out_path=path_ind, prefix=paste("counts", coord, sep="_"), set=set, comparison=comp, ylab="Read count"))
###