### Author: Alexander Kanitz
### Created: 04-FEB-2013
### Modified: 04-FEB-2013
### Description: Plots window position counts generated by overlap_counts_window_around_pos_vs_bed.pl. The indicated window size as well as the innermost 10% of the indicated size are plotted.
### Arguments: 1. output table file generated by overlap_counts_window_around_pos_vs_bed.pl; 2. window size; 3. output path (may not include trailing!)
### Output: Plots of average and individual window position counts the positions specified in the input file; windows to be plotted are of the indicated size and of 10% of that value, both centered around the window mid-point (0); the actual window size is thus the indicated window size + 1; a window size parameter of 100,000 will plot windows of 100,001 and 10,001
### Usage: Rscript ./plot_window_position_counts.R window_size/integer output_path

### Initialize and get command line arguments
args <- commandArgs(trailingOnly=TRUE)
###

### Load data
# Read data table
df <- read.table(args[1], sep=" ", row.names=1, fill=TRUE)
## Determine sizes for big and small windows; IF window size is set and not bigger than number of data columns... 
if ((as.integer(args[2]) < ncol(df))) {
	# ...set big window size to indicated value
	win_size_l <- as.integer(args[2])
	# ...set small window size to one tenth of indicated value
	win_size_s <- as.integer(args[2]) / 10
## ELSE...
} else {
	# ...set big window size to total number of data columns
	win_size_l <- ncol(df) - 1
	# ...set small window size to one tenth of the total number of data columns
	win_size_s <- (ncol(df) - 1) / 10
}
###


### Build output paths
# Build path name for average count plots
path_avg <- paste(args[3], "/average_counts/", sep="")
# Build path name for individual count plots
path_ind <- paste(args[3], "/individual_counts/", sep="")
# Create dir for average count plots
dir.create <- dir.create(path_avg, showWarnings = TRUE, mode = "0755")
# Create dir for individual count plots
dir.create <- dir.create(path_ind, showWarnings = TRUE, mode = "0755")
###

### Plots for indicated window size
## Subset data
# Generate logical vector indicating which columns to subset
cols_l <- c	(rep( FALSE, ( (ncol(df) - win_size_l) / 2 )), rep( TRUE , (win_size_l + 1)), rep( FALSE, (((ncol(df) - win_size_l) / 2))))
# Subset dataframe
df_l <- subset(df, select=cols_l)
# Generate x axis labels (window positions centered around 0)
x_l <- seq(-(win_size_l / 2), win_size_l / 2, 1)
##

## Plot average window counts
# Compute averages
y_l <- colSums(df_l) / nrow(df_l)
# Build output plot name
name_l <- paste(path_avg, basename(args[1]), "_", win_size_l, "_means.pdf", sep="")
# Open pdf printer device
pdf(name_l, width = 24, height = 8)
# Plot
plot(x_l, y_l, type="l", main=paste("file: ", basename(args[1]), "; motif: all (means); window size: ", win_size_l, sep=""), xlab="Position relative to AsiSI motifs", ylab="Read count average")
# Close pdf printer
dev.off()
##

## Plot individual window counts by applying a plotting function over each rowname of the data frame
sapply(rownames(df_l), function(row) {
	# Build output plot names
	name_l <- paste(path_ind, basename(args[1]), "_", win_size_l, "_", row, ".pdf", sep="")
	# Open pdf printer device
	pdf(name_l, width = 24, height = 8)
	# Plot
	plot(x_l, df_l[row, ], type="l", main=paste("file: ", basename(args[1]), "; motif: ", row, "; window size: ", win_size_l, sep=""), xlab="Position relative to AsiSI motifs", ylab="Read counts")
	# Close pdf printer
	dev.off()
})	
###


### Plots for innermost 10% of indicated window size
## Subset data
# Generate logical vector indicating which columns to subset
cols_s <- c(rep(FALSE, ((win_size_l - win_size_s) / 2)), rep(TRUE, (win_size_s + 1)), rep(FALSE, ((win_size_l - win_size_s) / 2)))
# Subset dataframe
df_s <- subset(df_l, select=cols_s)
# Generate x axis labels (window positions centered around 0)
x_s <- seq(-(win_size_s / 2), (win_size_s / 2), 1) 
##

## Plot average window counts
# Compute averages
y_s <- colSums(df_s) / nrow(df_s)
# Build output plot name
name_s <- paste(path_avg, basename(args[1]), "_", win_size_s, "_means.pdf", sep="")
# Open pdf printer device
pdf(name_s, width = 24, height = 8)
# Plot
plot(x_s, y_s, type="l", main=paste("file: ", basename(args[1]), "; motif: all (means); window size: ", win_size_s, sep=""), xlab="Position relative to AsiSI motifs", ylab="Read count average")
# Close pdf printer
dev.off()
##

## Plot individual window counts by applying a plotting function over each rowname of the data frame
sapply(rownames(df_s), function(row) {
	# Build output plot names
	name_s <- paste(path_ind, basename(args[1]), "_", win_size_s, "_", row, ".pdf", sep="")
	# Open pdf printer device
	pdf(name_s, width = 24, height = 8)
	# Plot
	plot(x_s, df_s[row, ], type="l", main=paste("file: ", basename(args[1]), "; motif: ", row, "; window size: ", win_size_s, sep=""), xlab="Position relative to AsiSI motifs", ylab="Read counts")
	# Close pdf printer
	dev.off()
})
###