#!/bin/bash

## Alexander Kanitz
## 24-MAR-2015

## Paste (headless) regular and extended qstat output
paste \
<( qstat | tail -n +3 ) \
<( qstat -ext -r | tail -n +3 | sed ':a;N;$!ba;s/\n       /\t/g' ) | \
## Replace spaces (single or multiple) with tabs
sed 's/ \+/\t/g' | \
## Parameter extraction and printing
awk '	## Print header
	BEGIN { 
		printf "%-7s %-10s %-2s %-11s %2s %4s %6s %-3s %8s %10s %5s\n",
			"ID", "Name", "St", "Subm/start", "#", "lMEM", "lRT", "Hst", "cpuRT", "accMem", "I/O"
		print gensub(/0/, "-", "g", sprintf("%0*d", 78, 0));
	}
	## Print main
	{
		## Grab state-independent parameters of interest
		job_id=$1
		state=$5
		$6=substr($6,0,5)
		$7=substr($7,0,5)
		submit_start=($6","$7)
		## For running jobs...
		if (state == "r") {
			## Grab state-dependent parameters of interest
			slots=$9
			cpu=substr($18,0,length($18)-3)
			mem=$19
			io=$20
			## Extract parameters whose position may vary
			for (i = 1; i <= NF; i++) {
				if ($i == "Full" && $(i+1) == "jobname:") jobname = $(i+2)
				if ($i == "Master" && $(i+1) == "Queue:") queue_host = $(i+2)
				if ($i ~ "^h_vmem" ) split($i, mv, "=")
				if ($i ~ "^d_rt" ) split($i, max_rt, "=")
			}
			split(queue_host, qh, "@")
			split(qh[2], host, ".")
			split(host[1], node, "-")
			max_vmem = substr(mv[2], 0, length(mv[2])-1)
			## Print parameters
			printf "%-7s %-10.10s %-2s %11s %2d %4s %6s %3s %8.8s %10.0f %5.0f\n",
				job_id, jobname, state, submit_start, slots, max_vmem*slots"G", max_rt[2]/3600"h", node[2], cpu, mem, io
		}
		## For waiting jobs...
		else if (state == "qw") {
			## Grab state-dependent parameters of interest
			slots=$8
			## Extract parameters whose position may vary
			for (i = 1; i <= NF; i++) {
				if ($i == "Full" && $(i+1) == "jobname:") jobname = $(i+2)
				if ($i == "Hard" && $(i+1) == "requested" && $(i+2) == "queues:") queue = $(i+3)
				if ($i ~ "^h_vmem" ) split($i, mv, "=")
				if ($i ~ "^d_rt" ) split($i, max_rt, "=")
			}
			max_vmem = substr(mv[2], 0, length(mv[2])-1)
			## Print parameters
			printf "%-7s %-10.10s %-2s %11s %2d %4s %6s\n",
				job_id, jobname, state, submit_start, slots, max_vmem*slots"G", max_rt[2]/3600"h"
		}
		## For all other jobs
		else {
			## Extract parameters whose position may vary
			for (i = 1; i <= NF; i++) {
				if ($i == "Full" && $(i+1) == "jobname:") jobname = $(i+2)
				if ($i == "Hard" && $(i+1) == "requested" && $(i+2) == "queues:") queue = $(i+3)
			}
			## Print parameters
			printf "%-7s %-10.10s %-2s %11s\n",
				job_id, jobname, state, submit_start
		}
	}'
