#!/bin/bash

## Alexander Kanitz
## 24-MAR-2015

## Paste (headless) regular and extended qstat output
paste \
<( qstat | tail -n +3 ) \
<( qstat -ext -r | tail -n +3 | sed ':a;N;$!ba;s/\n       /\t/g' ) | \
## Replace spaces (single or multiple) with tabs
sed 's/ \+/\t/g' | \
## Parameter extraction and printing
awk '	## Print header
	BEGIN { 
		printf "%-7s  %-52s  %-5s  %-11s  %-19s  %5s  %-8s  %-8s  %-23s  %11s  %12s  %7s\n",
			"ID", "Name", "State", "Queue", "Submit/start", "Slots", "Max_vmem", "Max_time", "Host", "CPU_time", "Acc_Mem", "Acc_I/O"
		print gensub(/0/, "-", "g", sprintf("%0*d", 190, 0));
	}
	## Print main
	{
		## Grab state-independent parameters of interest
		job_id=$1
		state=$5
		submit_start=($6","$7)
		## For running jobs...
		if (state == "r") {
			## Grab state-dependent parameters of interest
			slots=$9
			cpu=$18
			mem=$19
			io=$20
			## Extract parameters whose position may vary
			for (i = 1; i <= NF; i++) {
				if ($i == "Full" && $(i+1) == "jobname:") jobname = $(i+2)
				if ($i == "Master" && $(i+1) == "Queue:") queue_host = $(i+2)
				if ($i ~ "^h_vmem" ) split($i, mv, "=")
				if ($i ~ "^d_rt" ) split($i, max_rt, "=")
			}
			split(queue_host, qh, "@")
			split(qh[2], host, ".")
			max_vmem = substr(mv[2], 0, length(mv[2])-1)
			## Print parameters
			printf "%-7s  %-52.52s  %-5s  %-11s  %19s  %5d  %8s  %8s  %23s  %11.11s  %12.1f  %7.1f\n",
				job_id, jobname, state, qh[1], submit_start, slots, max_vmem*slots"G", max_rt[2]/3600"h", qh[2], cpu, mem, io
		}
		## For waiting jobs...
		else if (state == "qw") {
			## Grab state-dependent parameters of interest
			slots=$8
			## Extract parameters whose position may vary
			for (i = 1; i <= NF; i++) {
				if ($i == "Full" && $(i+1) == "jobname:") jobname = $(i+2)
				if ($i == "Hard" && $(i+1) == "requested" && $(i+2) == "queues:") queue = $(i+3)
				if ($i ~ "^h_vmem" ) split($i, mv, "=")
				if ($i ~ "^d_rt" ) split($i, max_rt, "=")
			}
			max_vmem = substr(mv[2], 0, length(mv[2])-1)
			## Print parameters
			printf "%-7s  %-52.52s  %-5s  %-11s  %19s  %5d  %8s  %8s\n",
				job_id, jobname, state, queue, submit_start, slots, max_vmem*slots"G", max_rt[2]/3600"h"
		}
		## For all other jobs
		else {
			## Extract parameters whose position may vary
			for (i = 1; i <= NF; i++) {
				if ($i == "Full" && $(i+1) == "jobname:") jobname = $(i+2)
				if ($i == "Hard" && $(i+1) == "requested" && $(i+2) == "queues:") queue = $(i+3)
			}
			## Print parameters
			printf "%-7s  %-52.52s  %-5s  %-11s  %19s\n",
				job_id, jobname, state, queue, submit_start
		}
	}'
